[cisco_switches]
switch1 ansible_host=192.168.0.130
switch2 ansible_host=192.168.0.120

[cisco_switches:vars]
ansible_user=admin
ansible_password=K@sr@1377
ansible_connection=ansible.netcommon.network_cli
ansible_network_os=cisco.ios.ios
ansible_become=yes
ansible_become_method=enable
ansible_become_password=K@sr@1377
